# Generated by Django 4.2.3 on 2023-07-22 12:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cat_name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tagname', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('like', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('Tashkent', 'Tashkent'), ('Andijon', 'Andijon'), ('Farg`ona', 'Farg`ona'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Jizzax', 'Jizzax'), ('Sirdaryo', 'Sirdaryo'), ('Toshkent viloyat', 'Toshkent viloyat'), ('Qoraqalpog`iston res', 'Qoraqalpog`iston res'), ('Xorij', 'Xorij')], default='Tashkent', max_length=30)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('teg', models.ManyToManyField(to='news.teg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
